image: gitlab.alelec.net:5004/gitlab-buildbot/devpi_client_manylinux:i686-latest

before_script:
  - export PATH=/opt/python/cp35-cp35m/bin:$PATH
  - pip install nose yanc requests PyWebDAV3
  - pip install --editable .

stages:
  - test
  - deploy

test:
  stage: test
  variables:
    PYTHONASYNCIODEBUG: "1"
  script:
  - nosetests -v --with-yanc --nologcapture --nocapture -w tests

deploy:
  stage: deploy
  script:
  - sed -i "s/<username>/$PYPI_USER/" ~/.pypirc
  - sed -i "s/<password>/$PYPI_PASS/" ~/.pypirc
  - devpi use $DEVPI_SERVER
  - devpi login $DEVPI_USER --password $DEVPI_PASS
  - devpi use $DEVPI_USER/prod
  - devpi upload
  - devpi push aioeasywebdav==`python setup.py --version` pypi:pypi
  only:
  - tags
  - master
